services:
  demo_redis:
    user: 1000:1000
    image: redis:6.0-alpine
    container_name: demo_reddis
    restart: always
    environment:
      - REDIS__PASSWORD=${REDIS__PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS__PASSWORD}" ]
    networks:
      - demo_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/data/redis:/data
    ports:
      - 6378:6379

  bet_maker_app:
    build:
      context: .
      dockerfile: docker/BetMaker.dockerfile
    image: bet_maker_app
    container_name: bet_maker_app
    env_file: .env
    restart: always
    volumes:
      - ./bet_maker:/app/src
    networks:
      - demo_network
    ports:
      - "8081:80"

networks:
  demo_network:
    external: true
    name: demo_network